spring.application.name=expense
server.port=9090

#Database Configurations
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/expense_db?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#dialect: (important for query optimization)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#path config
#user.profile.image.path=images/users

#file config
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
blank_profile_url=https://res.cloudinary.com/dqqkklbpp/image/upload/v1765531233/ExpenseManagement/zxzdlf9vjqutgynrwsa8.png

#JWT Configurations
#jwt_secret=ExpenseManagement12345withSpringBoot2025withJWTkvcihsifvisnbvisbdcvibsivbisbvisbvibsibvisbvibsivbisvbisbvibsivbisdbvisbvibsivb
jwt_expiration=3600000

#Spring Mail Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Cloudinary Configurations
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}
cloudinary.folder.upload=${CLOUD_FOLDER_UPLOAD}

# Twillo Configurations
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.from-number=${TWILIO_FROM_NUMBER}
twilio.verify-service-sid=${TWILIO_VERIFY_SERVICE_SID}


# Google OAuth2 Config
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:9090/api/auth/google/callback
#spring.security.oauth2.client.registration.google.scope=profile,email

# Google OAuth2 Custom Config
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=http://localhost:9090/api/auth/google/callback
google.auth-uri= https://accounts.google.com/o/oauth2/v2/auth
security.oauth.state-key= 949774974959797abcdbabcbabcbcbacbabcbacee27537253727537825873585


# Redis configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# gives RedisCommandTimeoutException if timeout occurs (in milliseconds)
spring.data.redis.timeout=3s
# TCP connection timeout, Time allowed to establish connection, Important when Redis is down or unreachable
# gives RedisConnectionFailureException if connection timeout
spring.data.redis.connect-timeout=1000
spring.data.redis.password=${REDIS_PASSWORD}

# Resilience4j Pattern to define configurations
# resilience4j.retry.instances.<INSTANCE_NAME>.*
# resilience4j.circuitbreaker.instances.<INSTANCE_NAME>.*

# Resilience4j - Retry
# Total attempts = 1 original + 1 retry, Handles short network blips, Avoids long delays
resilience4j.retry.instances.redisRetry.max-attempts=2
# Wait 100 ms before retrying
resilience4j.retry.instances.redisRetry.wait-duration=100ms
# Retry only on Redis connection & command failures, Prevents retrying unsafe/logical errors conditions
resilience4j.retry.instances.redisRetry.retry-exceptions=\
org.springframework.data.redis.RedisConnectionFailureException,\
org.springframework.data.redis.RedisSystemException,\
io.lettuce.core.RedisConnectionException,\
io.lettuce.core.RedisCommandTimeoutException,\
io.netty.channel.ConnectTimeoutException
# Do not retry on other exceptions
resilience4j.retry.instances.redisRetry.ignore-exceptions=\
com.manage_expense.exceptions.RateLimitExceededException


# Resilience4j - Circuit Breaker
# Evaluate failures based on number of calls, not time
resilience4j.circuitbreaker.instances.redisCB.sliding-window-type=COUNT_BASED
# Last 10 calls are evaluated
resilience4j.circuitbreaker.instances.redisCB.sliding-window-size=10
# If failures are greater or equal 50% then fails - circuit opens
resilience4j.circuitbreaker.instances.redisCB.failure-rate-threshold=50
# Circuit stays OPEN for 10 seconds, No Redis calls, Immediate fallback
resilience4j.circuitbreaker.instances.redisCB.wait-duration-in-open-state=10s
# Allow 3 test calls after open state
resilience4j.circuitbreaker.instances.redisCB.permitted-number-of-calls-in-half-open-state=3
#Circuit breaker activates only after 5 calls (prevents false positives at startup)
resilience4j.circuitbreaker.instances.redisCB.minimum-number-of-calls=5
# record only mentioned exceptions as failures
resilience4j.circuitbreaker.instances.redisCB.record-exceptions=\
org.springframework.data.redis.RedisConnectionFailureException,\
org.springframework.data.redis.RedisSystemException,\
io.lettuce.core.RedisConnectionException,\
io.lettuce.core.RedisCommandTimeoutException,\
io.netty.channel.ConnectTimeoutException
# do not record other exceptions as failures
resilience4j.circuitbreaker.instances.redisCB.ignore-exceptions=\
com.manage_expense.exceptions.RateLimitExceededException

# RabbitMQ configuration (http://localhost:15672 for RabbitMQ management UI)
spring.rabbitmq.host=${RabbitMQ_HOST:localhost}
spring.rabbitmq.port=${RabbitMQ_PORT:5672}
spring.rabbitmq.username=${RabbitMQ_USERNAME}
spring.rabbitmq.password=${RabbitMQ_PASSWORD}
spring.rabbitmq.virtual-host=/
# Enable publisher confirms & returns
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# Consumer reliability
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=5000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Swagger UI Configurations
# (method: sort by HTTP method (GET, PUT, POST etc..), alpha: sort alphabetically, none: no sorting)
#springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha